### ISSUE TITLE
how to control fans?

### ISSUE THREAD

**Issue by kostya4000** [FreeJHack/ClevoService#1]
how to control fans?

**Comment by FreeJHack** [comment]
Not yet fully implemented, maybe in the future...
However, the (BIOS) automatic mode of my P970EF with Mojave 18G2022 controls all 3 fans' speed according to temperature. This perfectly fits my needs.
Even the manual mode Fn+1 to fully boost all fans is working.

**Comment by kostya4000** [comment]
Thanks, Fn + 1 works for me
