### ISSUE TITLE
Keyboard backlight not available

### ISSUE THREAD

**Issue by mangguomax** [FreeJHack/ClevoService#2]
Hello, after I load SSDT, the keyboard control is still unavailable. FN + "*" has no response. What's the reason?

**Comment by FreeJHack** [comment]
Most probably you didn't patch your ACPI as per "How To Install".
If you're using Clover, you need to patch two methods: _WAK & _Q50.
You can check whether everything is fine using the IORegistryExplorer. You have to find the device CLV0 with attached ClevoKbdFanService (look at attached pict)
![CLV0](https://user-images.githubusercontent.com/22559967/74609633-20bd4400-50ec-11ea-84c2-54dcca2327bb.png)

**Comment by mangguomax** [comment]
> 您很可能没有按照“如何安装”对ACPI进行修补。
> 如果使用的是四叶草，则需要打补丁两种方法：_WAK和_Q50。
> 您可以使用IORegistryExplorer检查一切是否正常。您必须找到附带ClevoKbdFanService的设备CLV0（请参阅附带的pict）
> ![CLV0](https://user-images.githubusercontent.com/22559967/74609633-20bd4400-50ec-11ea-84c2-54dcca2327bb.png)

**Comment by mangguomax** [comment]
<img width="740" alt="1" src="https://user-images.githubusercontent.com/61035110/74611855-ca2b2680-513a-11ea-8524-6c34f0a70af3.png">
<img width="1402" alt="2" src="https://user-images.githubusercontent.com/61035110/74611858-d2836180-513a-11ea-838a-efb3a1d1b9bf.png">
<img width="908" alt="3" ### src="https://user-images.githubusercontent.com/61035110/74611861-d7481580-513a-11ea-864a-8d29004c444f.png">

**Comment by mangguomax** [comment]
I used OC, and have modified _WAK & _Q50, and found the device clv0 with clevokbdfanservice, but the keyboard backlight is still not available

**Comment by mangguomax** [comment]
I use the open core, and have modified the _WAK & _Q50., and found the device clv0 with clevokbdfanservice, but the keyboard backlight is still not available

**Comment by FreeJHack** [comment]
ClevoService is using the device **DCHU** to communicate with laptop hardware (through ACPI).
When CLV0 is loaded, the property KBLT is showing the actual keyboard backlight status.

![Schermata 2020-02-16 alle 23 18 02aa](https://user-images.githubusercontent.com/22559967/74614048-c4224f00-5114-11ea-9059-6d2f5f17e8aa.png)

According to your IOReg this device is missing, this is the reason why it's not working...

How to fix:
in your DSDT (even in IOReg) the device WMI should be also available

![Schermata 2020-02-16 alle 23 45 49](https://user-images.githubusercontent.com/22559967/74614254-a81fad00-5116-11ea-936f-b686dd29a7e3.png)

In addition, check if in your DSDT it is also available the method **WMBB** (attach your DSDT to your reply). It should looks like below

            Method (WMBB, 3, NotSerialized)
            {
                Store (Acquire (^^PCI0.LPCB.EC.PATM, 0x0064), Local1)
                If (LEqual (Local1, Zero))
                {
                    If (LEqual (ToInteger (Arg1), 0x0C))
                    {
                        Store (DEVT (Arg0, Arg1, Arg2), Local0)
                        Release (^^PCI0.LPCB.EC.PATM)
                        Return (Local0)
                    }
                    ElseIf (LEqual (ToInteger (Arg1), 0x0D))
                    {
                        Store (EEVT (Arg0, Arg1, Arg2), Local0)
                        Release (^^PCI0.LPCB.EC.PATM)
                        Return (Local0)
                    }
                    ElseIf (LEqual (ToInteger (Arg1), 0x0E))
                    {
                        Store (FEVT (Arg0, Arg1, Arg2), Local0)
                        Release (^^PCI0.LPCB.EC.PATM)
                        Return (Local0)
                    }
                    Else
                    {
                        Store (ZEVT (Arg0, Arg1, Arg2), Local0)
                        Release (^^PCI0.LPCB.EC.PATM)
                        Return (Local0)
                    }
                }
            }

If available, I have to implement support for WMBB as an alternative to DCHU when it's missing.
In the meantime, you could patch the SSDT-ClevoService file yourself by changing
Method (CLVE, 3, Serialized)
{
       \_SB.DCHU.ZEVT (Arg0, Arg1, Arg2)
}
to
Method (CLVE, 3, Serialized)
{
       \_SB.WMI.WMBB (Arg0, Arg1, Arg2)
}
It should works...

**Comment by mangguomax** [comment]
After checking in ioreg, I found that dchu was indeed lost. Later, I changed _SB.DCHU.ZEVT (Arg0, Arg1, Arg2) to _SB.WMI.WMBB (Arg0, Arg1, Arg2) according to the method you provided. After that, I can use the keyboard backlight normally and use it perfectly. Thank you for your help!

[dsdt.zip](https://github.com/FreeJHack/ClevoService/files/4211882/dsdt.zip)

**Comment by FreeJHack** [comment]
Good...
The SSDT file in the repository has been updated .
