### ISSUE TITLE
Clevo P650-HP6 autodim brightness isn't restored when typing.

### ISSUE THREAD

**Issue by gmct** [FreeJHack/ClevoService#3]
First off, I just wanted to say thank you so much for building out this plugin. I'm considering throwing together a GUI on top of it that'll allow full customization of color and other setting changes if possible. I've recently hackintoshed my P650 HP6 on Catalina and I'm finding that after the keyboard backlight dims it doesn't restore brightness by pressing any of the keys unless I press the backlight adjustment keys.
It's not a terrible issue and for now I'll just disable autodim, but I figured I'd bring it up to get some community engagement going.

**Comment by FreeJHack** [comment]
No problem on Mojave (18G5033) and previous versions but I cannot test on Catalina now, however, you may want to install the attached pre-release of debug version 1.2.0 (will be released soon...). After installing and rebooting, open console and filter for "Clevo" messages and post the results.
You should find something like this:

ClevoService: LogAction called with eventType 10
ClevoService: Key Down, Timer Reloaded 180000 mS
ClevoService: LogAction called with eventType 11

everytime you press a key.
Maybe Catalina is doing something different...
Thanks
[ClevoService.kext.zip](https://github.com/FreeJHack/ClevoService/files/4697500/ClevoService.kext.zip)

**Comment by FreeJHack** [comment]
Tested today on Catalina 10.15.5 and it works correctly.

**Comment by gmct** [comment]
Hey, testing out the release you sent and I don't see any of those events popping up. What kext are you using for your keyboard?
