### ISSUE TITLE
Authentication error and unidentified developer

### ISSUE THREAD

**Issue by bugrasrt** [FreeJHack/ClevoService#4]
Big Sur(11.1) can't verify ClevoService.kext and doesn't want to load and initialize. It says authentication error and unidentified developer. Every attempt of LaunchAgent is causing to unidentified developer popup. So do i need SIP disabled or i must build myself from Xcode ? Thanks.

**Comment by FreeJHack** [comment]
The Kext and the Agent are not signed, you can build 'em adding your own signature (if you're a developer...) or you need to disable SIP.

**Comment by bugrasrt** [comment]
Alright, thanks.
